server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://pj-op: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@github.com/pj-op/spring-cloud-config-configurations.git
#Private Git repo with personal access token:
#         https://<username>:<personal-access-token>@github.com/pj-op/spring-cloud-config-configurations.git